Drop the matrix for now

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -6,16 +6,16 @@ jobs:
   test:
     name: Run tests
     runs-on: ubuntu-latest
-    continue-on-error: ${{ matrix.experimental }}
-    strategy:
-      fail-fast: false
-      matrix:
-        codespell_pip_version: ['codespell']
-        experimental: [false]
-        include:
-          - codespell_pip_version: 'git+https://github.com/codespell-project/codespell.git'
-            # Set this to true if git master is breaking the action's tests
-            experimental: false
+    #continue-on-error: ${{ matrix.experimental }}
+    #strategy:
+    #  fail-fast: false
+    #  matrix:
+    #    codespell_pip_version: ['codespell']
+    #    experimental: [false]
+    #    include:
+    #      - codespell_pip_version: 'git+https://github.com/codespell-project/codespell.git'
+    #        # Set this to true if git master is breaking the action's tests
+    #        experimental: false
 
     steps:
       - name: Checkout
@@ -24,8 +24,10 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
 
-      - name: Install codespell via pip using ${{ matrix.codespell_pip_version }}
-        run: pip3 --quiet --quiet install ${{ matrix.codespell_pip_version }}
+     # - name: Install codespell via pip using ${{ matrix.codespell_pip_version }}
+     #   run: pip3 --quiet --quiet install ${{ matrix.codespell_pip_version }}
+      - name: Install codespell via pip
+        run: pip3 --quiet --quiet install git+https://github.com/codespell-project/codespell.git
 
       - name: Install Bats
         run: |
@@ -64,7 +66,7 @@ jobs:
   diagnose_bats:
     name: Diagnose bats
     needs: test
-    if: always() && contains(needs.*.status, 'failure')
+    if: always() && (contains(needs.*.status, 'failure') || (needs.test.status == 'failure') || (needs.test.failure) || (needs.test.failure()))
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
